=== iambasanta/cc/5th-sem/web/xml/report.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for XML Lab Session -->
<!ELEMENT Report (Metadata, Body)>
<!ELEMENT Metadata (Author+, Assignment)>
<!ELEMENT Author (Name, Email, (HomePhone | WorkPhone)?)>
<!ELEMENT Assignment (Course, Date, Title, Description?)>
<!ELEMENT Body (Section)+>
<!ELEMENT Section (Para)+>
 
<!ATTLIST Author
affiliation CDATA #FIXED "IOE"
>
<!ATTLIST Section
title CDATA #REQUIRED
id ID #IMPLIED
>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT HomePhone (#PCDATA)>
<!ELEMENT WorkPhone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Course (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Para (#PCDATA)>
<!ATTLIST Assignment
AssCode NMTOKEN #IMPLIED
>

=== iambasanta/cc/5th-sem/web/xml/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Report SYSTEM "report.dtd">
<Report>
<Metadata>
<Author>
<Name>Madan Kadariya</Name>
<Email>madan.kadariya@ncit.edu.np</Email>
<WorkPhone>4356789</WorkPhone>
</Author>
<Author>
<Name>Your name</Name>
<Email>Your email</Email>
<HomePhone>your phone</HomePhone>
</Author>
<Assignment>
<Course>Semantic Web</Course>
<Date>11 June 2021</Date>
<Title>Title of Assignment</Title>
<Description>Short description of the assignment.</Description>
</Assignment>
</Metadata>
<!-- This is a comment -->
<Body>
<Section title="Section 1 title" id="s1">
<Para>Paragraph 1 goes here</Para>
<Para>This is a unicode character reference &#960;. Here are some entity
 
references - &amp;,&apos;,&gt;,&lt;,&quot;</Para>
 
</Section>
<Section title="Section 2 title" id="s2">
<Para><![CDATA[ Anything goes in CDATA ..& more here ......<and>
 
here....]]></Para>
 
<Para>Paragraph 2 goes here</Para>
</Section>
</Body>
</Report>
